ForumETF/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace ForumETF.Models
{
    public class Post
    {
        public Post()
        {
            CreatedAt = DateTime.Now;
            UpdatedAt = DateTime.Now;
            IsApproved = false;
        }

        public int PostId { get; set; }

        [Required]
        public string Title { get; set; }
        [AllowHtml]
        public string Content { get; set; }
        public int Votes { get; set; }
        public bool IsApproved { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        public virtual AppUser User { get; set; }
        public virtual Category Category { get; set; }

        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<PostAttachment> Attachments { get; set; }
    }
}

ForumETF/Controllers/AnswerController.cs
using System.Net;
using System.Web.Mvc;
using ForumETF.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ForumETF.Controllers
{
    public class AnswerController : Controller
    {
        private AppDbContext db = null;
        private UserManager<AppUser> manager = null;

        public AnswerController()
        {
            db = new AppDbContext();
            manager = new UserManager<AppUser>(new UserStore<AppUser>(db));
        }

        // GET: Answer
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public PartialViewResult Create(int post, string answer)
        {
            string content = WebUtility.HtmlDecode(answer);

            var currentUser = manager.FindById(User.Identity.GetUserId());
            var existingPost = db.Posts.Find(post);

            Answer new_answer = new Answer
            {
                Content = content,
                Post = existingPost,
                User = currentUser
            };

            db.Answers.Add(new_answer);
            db.SaveChanges();

            return PartialView("_NewAnswer", new_answer);
        }
    }
}

ForumETF/Controllers/PostController.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using ForumETF.Models;
using ForumETF.Repositories;
using ForumETF.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PagedList;
using AutoMapper;
using ForumETF.CustomAttributes;
using ForumETF.HtmlHelpers;

namespace ForumETF.Controllers
{
    [RoutePrefix("Post")]
    public class PostController : Controller
    {
        private readonly AppDbContext _db;
        private readonly UserManager<AppUser> _manager;
        private readonly IPostRepository _repo;

        public PostController ()
	    {
            _db = new AppDbContext();
            _manager = new UserManager<AppUser>(new UserStore<AppUser>(_db));
            _repo = new PostRepository(_db);
    	}

        [HttpGet]
        public ActionResult Create()
        {
            CreatePostViewModel viewModel = new CreatePostViewModel
            {
                Categories = new SelectList(_repo.PopulateCategoriesDropdown(), "Value", "Text")
            };
           
            return View(viewModel);
        }

        [HttpPost]
        [ValidateModel]
        public async Task<ActionResult> Create(CreatePostViewModel model)
        {
            var currentUser = await GetLoggedInUser();

            _repo.Create(model, GetPostAttachments(model.Files), currentUser);
            _repo.SavePost();

            model.Categories = new SelectList(_repo.PopulateCategoriesDropdown(), "Value", "Text");

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        //[Route("Details/{seoName}")]
        public ActionResult Details(int? postId, string seoName)
        {
            if (postId == null) 
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
      
            var post = _repo.GetPostById(postId);

            if (post == null) 
                return View("404");
           
            var viewModel = GeneratePostDetailsViewModel(post);

            if (seoName != HelperMethods.GetUrlSeoName(viewModel.Title))
                return RedirectToActionPermanent("Details",
                    new {postId = viewModel.PostId, seoName = HelperMethods.GetUrlSeoName(viewModel.Title)});

            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var post = _db.Posts.Find(id);

            return View(post);
        }

        [HttpPost]
        public ActionResult Edit(Post post)
        {
            return null;
        }

        [HttpPost]
        public ActionResult Delete(int postId)
        {
            var post = _db.Posts.Find(postId);

            _db.Posts.Remove(post);
            _db.SaveChanges();

            var postCount = _db.Posts.Count(p => p.User.UserName == User.Identity.Name);
          
            //return Json(new { num_of_posts = postCount });
            return RedirectToAction("GetPublishedPosts", "User");
        }

        //[Route("Tags/{tagName}")]
        public ActionResult GetPostsByTag(string tagName, int? page)
        {
            const int pageSize = 10;
            int pageNumber = (page ?? 1);

            var posts = _db.Posts.Where(p => p.Tags.Select(t => t.TagName).Contains(tagName))
                .OrderByDescending(p => p.CreatedAt)
                .ToPagedList(pageNumber, pageSize);

            ViewBag.Tag = tagName;
            
            return View("PostsByTag", posts);
        }

        public ActionResult GetPostsByCategory(string categoryName, int? page)
        {
            ViewBag.Category = categoryName;

            return View("PostsByCategory", _repo.GetPostsByCategory(categoryName, page));
        }

        public PartialViewResult MostPopularPosts(int? page)
        {
            return PartialView("_Content");
        }

        public PartialViewResult NewestPosts()
        {
            var posts = _db.Posts.OrderByDescending(p => p.CreatedAt).ToList();

            return PartialView("_Newest", posts);
        }

        public PartialViewResult UnansweredPosts()
        {
            var posts = _db.Posts.Where(p => p.Answers.Count == 0).OrderByDescending(p => p.CreatedAt).ToList();

            return PartialView("_Unanswered", posts);
        }

        /// <summary>
        /// Pomocna metoda koja omogucava download attachmenta
        /// </summary>
        /// <param name="filename"></param>
        /// <param name="postId"></param>
        /// <returns></returns>
        public FileStreamResult GetFile(string filename, int? postId)
        {
            var file = _db.PostAttachments.SingleOrDefault(a => a.Post.PostId == postId && a.FileName == filename);

            string path = file.FilePath;
            string mime = MimeMapping.GetMimeMapping(file.FileName);

            return File(new FileStream(path, FileMode.Open), mime, file.FileName);
        }

        #region private methods

        /// <summary>
        /// Pomocna metoda koja vraca novi Tag objekat ili vec postojeci Tag objekat, na osnovu parametra
        /// </summary>
        /// <param name="tagName"></param>
        /// <returns></returns>
        private Tag GetTag(string tagName)
        {
            return _repo.GetTag(tagName);
        }

        /// <summary>
        /// Pomocna metoda koja obradjuje upload fajlova
        /// </summary>
        /// <param name="files"></param>
        /// <returns></returns>
        private List<PostAttachment> GetPostAttachments(IEnumerable<HttpPostedFileBase> files)
        {
            List<PostAttachment> attachments = new List<PostAttachment>();

            foreach (var file in files)
            {
                if (file != null && file.ContentLength != 0)
                {
                    var filename = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/Uploads/Attachments"), filename);
                    file.SaveAs(path);
                    attachments.Add(new PostAttachment
                    {
                        FilePath = path,
                        FileName = filename
                    });
                }
            }

            return attachments;
        }

        /// <summary>
        /// Pomocna metoda koja asinhrono vraca objekat aktivnog korisnik
        /// </summary>
        /// <returns></returns>
        private async Task<AppUser> GetLoggedInUser()
        {
            return await _manager.FindByIdAsync(User.Identity.GetUserId());
        }

        /// <summary>
        /// Pomocna metoda koja kreira instancu PostDetailsViewModel klase na osnovu parametra post
        /// </summary>
        /// <param name="post"></param>
        /// <returns></returns>
        private PostDetailsViewModel GeneratePostDetailsViewModel(Post post)
        {
            Mapper.CreateMap<Post, PostDetailsViewModel>();
            var viewModel = Mapper.Map<PostDetailsViewModel>(post);
            var comments = _db.Comments.Where(c => c.Post.PostId == post.PostId).ToList();
            var answers = _db.Answers.Where(a => a.Post.PostId == post.PostId).ToList();
            //viewModel.Comments = comments;
            //viewModel.Answers = answers;
            viewModel.Comments = post.Comments.ToList();
            viewModel.Answers = post.Answers.ToList();

            return viewModel;
        }

       

        #endregion

    }
}

ForumETF/Views/Post/404.cshtml
@{
    ViewBag.Title = "404";
}

<h2>Error 404 - Stranica koju ste tražili ne postoji :(</h2>

ForumETF/Views/Post/Create.cshtml
@model CreatePostViewModel
@{
    ViewBag.Title = "Ovdje možete postaviti vaše pitanje";
}

<div class="row">
    <div class="col-md-12" id="post-create-wrapper">
        <section class="col-md-7">
            @using (Html.BeginForm("Create", "Post", FormMethod.Post, new { id = "createPostForm", @class = "form-horizontal", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <h3 style="color:  #03a9f4">@ViewBag.Title</h3>
                <h4>Polja označena zvjezdicom su obavezna!</h4>
                <hr />

                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        @Html.LabelFor(m => m.Title, "Naslov:", new { @class = "control-label" })
                    </div>
                    <div class="col-md-10 col-sm-10">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        @Html.LabelFor(m => m.Tags, "Tagovi:", new { @class = "control-label" })
                    </div>
                    <div class="col-md-10 col-sm-10">
                        @Html.EditorFor(m => m.Tags, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        @Html.Label("Kategorija: ", new { @class = "control-label" })
                    </div>
                    <div class="col-md-6 col-sm-6">
                        @Html.DropDownListFor(model => model.SelectedId, Model.Categories, "-- Izaberite kategoriju --", new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.SelectedId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        <label class="control-label">Tekst:</label>
                    </div>
                    <div class="col-md-10 col-sm-10" id="post-wysiwyg-wrapper">
                        @Html.TextAreaFor(m => m.Content)
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        @Html.LabelFor(m => m.Files, "Dodaci:", new { @class = "control-label" })
                    </div>

                    <div class="col-md-10 col-sm-10">
                        @Html.TextBoxFor(m => m.Files,
                                new { type = "file", @class = "filestyle", data_buttonBefore = "true", data_buttonText = "&nbspIzaberite fajl" })
                        @Html.TextBoxFor(m => m.Files,
                                new { type = "file", @class = "filestyle", data_buttonBefore = "true", data_buttonText = "&nbspIzaberite fajl" })
                    </div>
                </div>

                @Html.HiddenFor(m => m.Content)

                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
                        <input type="submit" id="post-save" value="Pošalji" class="btn btn-block btn-primary" />
                    </div>
                </div>
            }
        </section>
        <section class="col-md-5" id="rules-section">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><i class="fa fa-exclamation-circle"></i>&nbsp;&nbsp;Pravila za postavljanje pitanja</div>
                    <div class="panel-body">
                        <ul>
                            <li>Pravilo 1</li>
                            <li>Pravilo 2</li>
                            <li>Pravilo 3</li>
                            <li>Pravilo 4</li>
                            <li>Pravilo 5</li>
                            <li>Pravilo 6</li>
                            <li>Pravilo 7</li>
                            <li>Pravilo 8</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

ForumETF/Views/Post/Details.cshtml
@model PostDetailsViewModel

@{
    ViewBag.Title = "Details";
}

<div class="row" id="post-page-wrapper">
    <div class="col-md-12" id="post-details-wrapper">
        <div class="col-md-12" id="details-title">
            <h3>@Model.Title</h3>
            <hr />
        </div>
        <div class="col-md-12" id="details-body">
            <div class="col-md-1" id="ratings">
                <span><i class="fa fa-2x fa-chevron-up"></i></span>
                <span>@Model.Votes</span>
                <span><i class="fa fa-2x fa-chevron-down"></i></span>
                <span><i class="fa fa-2x fa-star-o"></i></span>
                <span>6</span>
            </div>
            <div class="col-md-11">
                @MvcHtmlString.Create(HttpUtility.HtmlDecode(Model.Content))
            </div>
        </div>
        <div class="col-md-11 col-md-offset-1" id="details-info">
            <div class="col-md-12" style="padding-bottom: 10px;">
                @foreach (var tag in Model.Tags)
                {
                    <a href="#" class="btn btn-xs btn-primary">@tag.TagName</a>
                }
            </div>
            <div class="col-md-12">
                @foreach (var file in Model.Attachments)
                {
                    <i class="fa fa-paperclip">&nbsp;&nbsp;</i><a href="@Url.Action("GetFile", "Post", new {filename = file.FileName, postId = Model.PostId})">@file.FileName</a>
                    @*@Html.ActionLink("Link download", "GetFile", "Post", new{filename = file.FileName, postId = Model.PostID}, null)*@
                    <br />
                }
            </div>
        </div>
    </div>

    <div class="col-md-12" id="post-comments-list">
        <div class="col-md-12">
            <div class="col-md-12" id="comments">
                @foreach (var comment in Model.Comments)
                {
                    <div class="col-md-8 col-md-offset-4">
                        <div class="col-md-12">
                            @comment.Content
                        </div>
                        <div class="col-md-12">
                            <a href="@Url.Action("Profile", "User", new {username = @comment.User.UserName})">@comment.User.UserName</a> | @comment.CreatedAt
                        </div>
                    </div>
                }
            </div>
            <hr/>
        </div>
        <div>
            @using (Ajax.BeginForm("Create", "Comment", new { post = @Model.PostId } , new AjaxOptions
            {
                UpdateTargetId = "comments", HttpMethod = "Post", InsertionMode = InsertionMode.InsertAfter
            }, new {id = "comment-form"}))
            {
                <!-- forma za kreiranje komentara -->
                <div class="form-group" style="padding-bottom: 30px;">
                    <div class="col-md-4 col-sm-2">
                        <label class="control-label">Vaš komentar</label>
                    </div>
                    <div class="col-md-8 col-sm-10">
                        <textarea class="form-control" name="commentContent" placeholder="Unesite vaš komentar"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
                        <input type="submit" id="comment-save" value="Pošalji" class="btn btn-block btn-primary" />
                    </div>
                </div>
            }
    </div>
</div>

<div class="col-md-12" id="post-answers-list">
    <div class="col-md-10 col-md-offset-2">
        @foreach (var answer in Model.Answers)
        {
            <div class="col-md-12">
                @answer.Content
            </div>
            <div class="col-md-12">
                @answer.User.UserName
            </div>
        }
    </div>
</div>

<div class="col-md-12" id="new-answer-area">
    @using (Ajax.BeginForm("Create", "Answer", new { post = @Model.PostId }, new AjaxOptions
    {
        UpdateTargetId = "answers",
        HttpMethod = "Post",
        InsertionMode = InsertionMode.InsertAfter
    }, new { id = "answer-form", @class = "form-horizontal" }))
    {
        <hr />
        <div class="form-group">
            <div class="col-md-2 col-sm-2">
                <label class="control-label">Tekst:</label>
            </div>
            <div class="col-md-10 col-sm-10" id="post-wysiwyg-wrapper">
                @Html.Partial("_RichEditor2")
            </div>
        </div>

        @Html.HiddenFor(m => m.Content)

        <div class="form-group">
            <div class="col-md-4 col-md-offset-2 col-sm-10 col-sm-offset-2">
                <input type="submit" id="answer-save" value="Pošalji" class="btn btn-block btn-primary" />
            </div>
        </div>
    }
</div>

</div>

ForumETF/Views/Post/Edit.cshtml
@model Post
@{
    ViewBag.Title = "Ovdje možete postaviti vaše pitanje";
}

<div class="row">
    <div class="col-md-12" id="post-create-wrapper">
        <section class="col-md-7">
            @using (Html.BeginForm("Edit", "Post", FormMethod.Post, new { id = "EditPostForm", @class = "form-horizontal", enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <h3 style="color:  #03a9f4">@ViewBag.Title</h3>
                <h4>Polja označena zvjezdicom su obavezna!</h4>
                <hr />

                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        @Html.LabelFor(m => m.Title, "Naslov:", new { @class = "control-label" })
                    </div>
                    <div class="col-md-10 col-sm-10">
                        @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        @Html.LabelFor(m => m.Tags, "Tagovi:", new { @class = "control-label" })
                    </div>
                    <div class="col-md-10 col-sm-10">
                        @Html.EditorFor(m => m.Tags, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
              
                <div class="form-group">
                    <div class="col-md-2 col-sm-2">
                        <label class="control-label">Tekst:</label>
                    </div>
                    <div class="col-md-10 col-sm-10" id="post-wysiwyg-wrapper">
                        @Html.TextAreaFor(m => m.Content)
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10 col-md-offset-2 col-sm-10 col-sm-offset-2">
                        <input type="submit" id="post-save" value="Pošalji" class="btn btn-block btn-primary" />
                    </div>
                </div>
            }
        </section>
        <section class="col-md-5" id="rules-section">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading"><i class="fa fa-exclamation-circle"></i>&nbsp;&nbsp;Pravila za postavljanje pitanja</div>
                    <div class="panel-body">
                        <ul>
                            <li>Pravilo 1</li>
                            <li>Pravilo 2</li>
                            <li>Pravilo 3</li>
                            <li>Pravilo 4</li>
                            <li>Pravilo 5</li>
                            <li>Pravilo 6</li>
                            <li>Pravilo 7</li>
                            <li>Pravilo 8</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

ForumETF/Views/Post/PostsByCategory.cshtml
@model PagedList.IPagedList<ForumETF.Models.Post>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<!-- search row -->
<div class="row" id="search-section">
    <div class="col-md-8">

        @using (Ajax.BeginForm("Index", "Home", new AjaxOptions
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "posts",
        }, new { id = "search-form" }))
        {
            <div class="col-md-8">
                <div class="form-group">
                    <input type="text" name="searchTerm" class="form-control" id="search" value="Unesite pojam za pretragu" />
                </div>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i>&nbsp;Pretraga</button>
            </div>
        }

    </div>
    <div class="col-md-8" id="home-page-filters">
        <div class="col-md-12">
            <h3>Postovi iz kategorije: @ViewBag.Category </h3>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8" id="posts">
        @Html.Partial("_Posts")
    </div>
    <div class="col-md-3 col-md-offset-1">

        @{
            Html.RenderAction("CategoriesWidget", "Home");
        }

        <div class="col-md-12">
            <h3>Tag cloud</h3>
            <br />
            <nav>
                <ul class="list-group">
                    <li class="list-group-item"><a href="#">Matematika</a></li>
                    <li class="list-group-item"><a href="#">Fizika</a></li>
                    <li class="list-group-item"><a href="#">Objektno orijentisano programiranje</a></li>
                    <li class="list-group-item"><a href="#">Programski jezici</a></li>
                    <li class="list-group-item"><a href="#">Opsti smjer</a></li>
                    <li class="list-group-item"><a href="#">Osnovi elektrotehnike 2</a></li>
                </ul>
            </nav>
        </div>
    </div>

</div>

ForumETF/Views/Post/PostsByTag.cshtml
@model PagedList.IPagedList<ForumETF.Models.Post>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<!-- search row -->
<div class="row" id="search-section">
    <div class="col-md-8">

        @using (Ajax.BeginForm("Index", "Home", new AjaxOptions
        {
            HttpMethod = "GET",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = "posts",
        }, new { id = "search-form" }))
        {
            <div class="col-md-8">
                <div class="form-group">
                    <input type="text" name="searchTerm" class="form-control" id="search" value="Unesite pojam za pretragu" />
                </div>
            </div>
            <div class="col-md-4">
                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i>&nbsp;Pretraga</button>
            </div>
        }

    </div>
    <div class="col-md-8" id="home-page-filters">
        <div class="col-md-12">
            <h3>Postovi oznaceni sa: </h3>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8" id="posts">
        @Html.Partial("_Posts")
    </div>
    <div class="col-md-3 col-md-offset-1">

        @{
            Html.RenderAction("CategoriesWidget", "Home");
        }

        <div class="col-md-12">
            <h3>Tag cloud</h3>
            <br />
            <nav>
                <ul class="list-group">
                    <li class="list-group-item"><a href="#">Matematika</a></li>
                    <li class="list-group-item"><a href="#">Fizika</a></li>
                    <li class="list-group-item"><a href="#">Objektno orijentisano programiranje</a></li>
                    <li class="list-group-item"><a href="#">Programski jezici</a></li>
                    <li class="list-group-item"><a href="#">Opsti smjer</a></li>
                    <li class="list-group-item"><a href="#">Osnovi elektrotehnike 2</a></li>
                </ul>
            </nav>
        </div>
    </div>

</div>

ForumETF/Views/Post/_AddComment.cshtml
@model ForumETF.Models.Comment

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ForumETF/Views/Post/_Content.cshtml
sdfsfsfsfsff

ForumETF/Views/Post/_DeleteConfirmed.cshtml
<h3>post je obrisan</h3>

ForumETF/Views/Post/_RichEditor.cshtml
@using (Ajax.BeginForm("Create", "Answer", new { post = Model.PostId }, new AjaxOptions
{
    HttpMethod = "Post",
    UpdateTargetId = "answers-area",
    InsertionMode = InsertionMode.InsertAfter
}
        ))
{
    <div class="form-group">

        <div class="col-md-12" id="markdown-wrapper">
            <div class="btn-toolbar" data-role="editor-toolbar" data-target="#markdown" id="markdown-toolbar">
                <div class="btn-group">
                    <a class="btn" title="" data-edit="bold" data-original-title="Bold (Ctrl/Cmd+B)"><i class="fa fa-bold"></i></a>
                    <a class="btn" title="" data-edit="italic" data-original-title="Italic (Ctrl/Cmd+I)"><i class="fa fa-italic"></i></a>
                    <a class="btn" title="" data-edit="strikethrough" data-original-title="Strikethrough"><i class="fa fa-strikethrough"></i></a>
                    <a class="btn" title="" data-edit="underline" data-original-title="Underline (Ctrl/Cmd+U)"><i class="fa fa-underline"></i></a>
                </div>
                <div class="btn-group">
                    <a class="btn" title="" data-edit="insertunorderedlist" data-original-title="Bullet list"><i class="fa fa-list-ul"></i></a>
                    <a class="btn" title="" data-edit="insertorderedlist" data-original-title="Number list"><i class="fa fa-list-ol"></i></a>
                    <a class="btn" title="" data-edit="outdent" data-original-title="Reduce indent (Shift+Tab)"><i class="fa fa-outdent"></i></a>
                    <a class="btn" title="" data-edit="indent" data-original-title="Indent (Tab)"><i class="fa fa-indent"></i></a>
                </div>
                <div class="btn-group">
                    <a class="btn" title="" data-edit="justifyleft" data-original-title="Align Left (Ctrl/Cmd+L)"><i class="fa fa-align-left"></i></a>
                    <a class="btn" title="" data-edit="justifycenter" data-original-title="Center (Ctrl/Cmd+E)">
                        <i class="fa fa-align-center"></i>
                    </a>
                    <a class="btn" title="" data-edit="justifyright" data-original-title="Align Right (Ctrl/Cmd+R)">
                        <i class="fa fa-align-right"></i>
                    </a>
                    <a class="btn" title="" data-edit="justifyfull" data-original-title="Justify (Ctrl/Cmd+J)">
                        <i class="fa fa-align-justify"></i>
                    </a>
                </div>
                <div class="btn-group">
                    <a class="btn" title="" data-edit="undo" data-original-title="Undo (Ctrl/Cmd+Z)">
                        <i class="fa fa-undo"></i>
                    </a>
                    <a class="btn" title="" data-edit="redo" data-original-title="Redo (Ctrl/Cmd+Y)">
                        <i class="fa fa-repeat"></i>
                    </a>
                </div>
            </div>
            <div id="markdown" contenteditable="true"></div>
        </div>
    </div>
    
    <input type="hidden" name="answer" id="answer-hidden" value="" />
    
    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Ostavi komentar" class="btn btn-default" id="answer-submit" />
        </div>
    </div>
}